name: camara_firebase_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: 2.4.3
  flutter_riverpod: 2.3.6
  riverpod_annotation: any
  camerawesome: 1.4.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
